### PR TITLE
fix issue #242

### LINKED ISSUE #242: In InitGenesis, the disordered and intermittent order will generate an error orderNum
## Summary of Bug

The InitGenesis of the order module is as follows
```
func InitGenesis(ctx sdk.Context, keeper keeper.Keeper, data GenesisState) {
	...
	// reset open order& depth book
	for _, order := range data.OpenOrders {
		height := types.GetBlockHeightFromOrderID(order.OrderID)
		...
		orderNum := keeper.GetBlockOrderNum(ctx, height)
		keeper.SetBlockOrderNum(ctx, height, orderNum+1)
		keeper.SetOrder(ctx, order.OrderID, order)
		...
	}
	...
}
```
Here, orderNum represents the number of orders, but not the maximum value of orderID.
For example, there are three orders in `data.OpenOrders`, `ID0005-5` `ID0005-3` `ID0005-8`. Then, `orderNum` is 3, not 8.

When we range the order according to block height, there will be some orders missing.
```
orderNum := k.GetBlockOrderNum(ctx, expiredBlockHeight)
var index int64
for ; index < orderNum; index++ {
	orderID := types.FormatOrderID(expiredBlockHeight, index+1)
	order := k.GetOrder(ctx, orderID)
	...
}
```
As shown in the above code, we will get `ID0005-3`, but no `ID0005-5` `ID0005-8`.

## Expected Result

In the above example, we expect `orderNum` is 8.

## Version

v0.10.8

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by xiangjianmeng**
close #242 

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/order/keeper/order.go [hunk 1]
```diff
@@ -100,3 +100,18 @@ func (k Keeper) quitOrder(ctx sdk.Context, order *types.Order, feeType string, l
 	k.RemoveOrderFromDepthBook(order, feeType)
 	return fee
 }
+
+func (k Keeper) ExpireOrdersInExpiredBlock(ctx sdk.Context, expiredBlockHeight int64) {
```
Comment (zhongqiuwood) [inline x/order/keeper/order.go]: DropExpiredOrdersByBlockHeight

Comment (zhongqiuwood) [inline x/order/keeper/order.go]: DropExpiredOrdersByBlockHeight
