### PR TITLE
fix #81 and add gov ut

### LINKED ISSUE #81: Params module does not provide query function
## Summary of Bug
when I query  the parameters of params module，no correct information returned

## Steps to Reproduce

command input:

```
1、$ okchaincli query params params

```
result:

```
Querying subcommands

Usage:
  okchaincli query [command]

Aliases:
  query, q

Available Commands:
  account                  Query account balance
              
  tendermint-validator-set Get the full tendermint validator set at given height
  block                    Get verified data for a the block at given height
  txs                      Query for paginated transactions that match a set of events
  tx                       Query for a transaction by hash in a committed block
              
  staking                  Querying commands for the staking module
  gov                      Querying commands for the governance module
  backend                  Querying commands for the backend module
  upgrade                  Querying commands for the upgrade module
  slashing                 Querying commands for the slashing module
  supply                   Querying commands for the supply module
  token                    Querying commands for the token module
  dex                      Querying commands for the dex module
  order                    Querying commands for the order module
  debug                    Debugging subcommands
  mint                     Querying commands for the minting module
  distr                    Querying commands for the distribution module

Flags:
  -h, --help   help for query

Global Flags:
      --chain-id string   Chain ID of tendermint node
  -e, --encoding string   Binary encoding (hex|b64|btc) (default "hex")
      --home string       directory for config and data (default "/root/.okchaincli")
  -o, --output string     Output format (text|json) (default "text")
      --passwd string     Pass word of sender (default "12345678")
      --trace             print out full stack trace on errors

Use "okchaincli query [command] --help" for more information about a command.


```

## Version
v0.10.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by xiangjianmeng**
Closes: #81

## Description

1.  fix issue #81
2. remove depositID and voteID
3. add gov ut
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [x] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/params/types/params.go [hunk 1]
```diff
@@ -35,3 +42,24 @@ func DefaultParams() Params {
 		MaxBlockHeight:   100000,
 	}
 }
+
+func (params Params) String() string {
```
Comment (RevelationOfTuring) [inline x/params/types/params.go:46]: different receiver name

File: x/params/types/params.go [hunk 2]
```diff
@@ -35,3 +42,24 @@ func DefaultParams() Params {
...
+MinDeposit:       %s,
+VotingPeriod:     %s,
+MaxBlockHeight:   %d,
+`, params.MaxDepositPeriod, params.MinDeposit, params.VotingPeriod, params.MaxBlockHeight)
+}
+
+// ParamSetPairs implements the ParamSet interface and returns all the key/value pairs
+// pairs of auth module's parameters.
+// nolint
+func (p *Params) ParamSetPairs() subspace.ParamSetPairs {
```
Comment (RevelationOfTuring) [inline x/params/types/params.go:58]: different reciever name
